version: '3.8'

services: 
  db_postgres:
    container_name: starter-kit-pg
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: starter-kit
      PGDATA: /data/postgres
    volumes: 
      - ./starter-kit-data/pg:/data/postgres
