services:
  postgres:
    container_name: starter-kit
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: starter-kit
      PGDATA: /data/postgres
    volumes:
      - ./starter-kit-data/pg:/data/postgres